Update README-he.md
jwasham/coding-interview-university pull request #1163
Opened 2022-07-09 19:55 UTC by avipars

Added more translation, still incomplete but better than the previous state.

2022-08-10 19:52 UTC, Itay-Kirsh requested changes

2022-08-10 19:52 UTC, Itay-Kirsh commented on translations/README-he.md
> +- [ ] **מינום**
מיונים

2022-08-10 19:52 UTC, Itay-Kirsh commented on translations/README-he.md
> +    - יש סרטונים למטה
ראו סרטונים להלן

2022-08-10 19:52 UTC, Itay-Kirsh commented on translations/README-he.md
> +- ### קומפיילרים
מהדרים

2022-08-10 19:52 UTC, Itay-Kirsh commented on translations/README-he.md
> +        - [פתרון](http://blog.panictank.net/category/algorithmndesignmanualsolutions/page/2/)
פתרונות

2022-08-10 19:52 UTC, Itay-Kirsh commented on translations/README-he.md
> +        - [פתרון](http://www.algorithm.cs.sunysb.edu/algowiki/index.php/The_Algorithms_Design_Manual_(Second_Edition))
פתרונות

2022-08-10 19:52 UTC, Itay-Kirsh commented on translations/README-he.md
> +# Coding Interview University אוניברסיטיה של ראיונות קוד
אוניברסיטה

2022-08-11 04:02 UTC, jwasham commented
Just noticed this. Sorry. Please see suggestions and let me know when you want to merge.

2022-08-31 20:50 UTC, merged

2022-08-31 20:50 UTC, jwasham commented
Thank you!