Add links to short review videos
jwasham/coding-interview-university pull request #1220
Opened 2022-09-10 01:08 UTC by msambol

2022-09-10 03:58 UTC, Tusharmalik007 commented
What's profession?

2022-09-14 16:12 UTC, jwasham requested changes

2022-09-14 16:12 UTC, jwasham commented on README.md
> +    - [ ] [[Review] Tree Traversal playlist by Michael Sambol (video)](https://www.youtube.com/playlist?list=PL9xmBV_5YoZO1JC2RgEi04nLy6D-rKk6b)
Remove your name from the line.

2022-09-14 16:12 UTC, jwasham commented on README.md
> +    - [ ] [[Review] Heap playlist by Michael Sambol (video)](https://www.youtube.com/playlist?list=PL9xmBV_5YoZNsyqgPW-DNwUeT8F8uhWc6)
Same as above.

2022-09-14 16:12 UTC, jwasham commented on README.md
> +    - [ ] [[Review] Tree Traversal playlist by Michael Sambol (video)](https://www.youtube.com/playlist?list=PL9xmBV_5YoZO1JC2RgEi04nLy6D-rKk6b)
I'd add the combined times of the playlist, like "Tree Traversals (playlist) in 11 minutes"

2022-09-14 16:12 UTC, jwasham commented on README.md
> +- [ ] [[Review] Sorting playlist by Michael Sambol](https://www.youtube.com/playlist?list=PL9xmBV_5YoZOZSbGAXAPIq1BeUf4j20pl)
Please remove your name from this and all others

2022-09-14 16:12 UTC, jwasham commented
See review. I like the idea of the quick reviews at the end of the sections :)

2022-09-14 17:09 UTC, msambol commented on README.md
> +    - [ ] [Insertion sort in 2 minutes (video)](https://youtu.be/JU767SDMDvA)
I removed the "[Review]" from each of the bullets. I thought it was too verbose, and the top states that it is review.

2022-09-14 18:14 UTC, merged

2022-09-14 18:14 UTC, jwasham commented
Thanks!