Adding programming resources
jwasham/coding-interview-university pull request #963
Opened 2021-09-07 21:20 UTC by nikita-jain-01

2021-09-07 22:59 UTC, sziolkow requested changes
Urls can be shorter

2021-09-07 22:59 UTC, sziolkow commented on programming-language-resources.md
> +    - [W3 Schools](https://www.w3schools.com/html/default.asp)
The url can be shorter: https://www.w3schools.com/html/

2021-09-07 22:59 UTC, sziolkow commented on programming-language-resources.md
> +    - [W3 Schools](https://www.w3schools.com/css/default.asp)
Same as above. The url doesn't need dafault.asp

2021-09-08 15:21 UTC, merged

2021-09-08 15:21 UTC, jwasham commented
Thanks!